export const input = ['ma-start',
    'YZ-rv',
    'MP-rv',
    'vc-MP',
    'QD-kj',
    'rv-kj',
    'ma-rv',
    'YZ-zd',
    'UB-rv',
    'MP-xe',
    'start-MP',
    'zd-end',
    'ma-UB',
    'ma-MP',
    'UB-xe',
    'end-UB',
    'ju-MP',
    'ma-xe',
    'zd-UB',
    'start-xe',
    'YZ-end'];

export const example1 = ['start-A',
    'start-b',
    'A-c',
    'A-b',
    'b-d',
    'A-end',
    'b-end'];

export const example2 = ['dc-end',
    'HN-start',
    'start-kj',
    'dc-start',
    'dc-HN',
    'LN-dc',
    'HN-end',
    'kj-sa',
    'kj-HN',
    'kj-dc'];

export const example3 = ['fs-end',
    'he-DX',
    'fs-he',
    'start-DX',
    'pj-DX',
    'end-zg',
    'zg-sl',
    'zg-pj',
    'pj-he',
    'RW-he',
    'fs-DX',
    'pj-RW',
    'zg-RW',
    'start-pj',
    'he-WI',
    'zg-he',
    'pj-fs',
    'start-RW'];