export const input = 'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 1\n' +
    'add x 11\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 5\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 1\n' +
    'add x 13\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 5\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 1\n' +
    'add x 12\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 1\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 1\n' +
    'add x 15\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 15\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 1\n' +
    'add x 10\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 2\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 26\n' +
    'add x -1\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 2\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 1\n' +
    'add x 14\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 5\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 26\n' +
    'add x -8\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 8\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 26\n' +
    'add x -7\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 14\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 26\n' +
    'add x -8\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 12\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 1\n' +
    'add x 11\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 7\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 26\n' +
    'add x -2\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 14\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 26\n' +
    'add x -2\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 13\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 26\n' +
    'add x -13\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 6\n' +
    'mul y x\n' +
    'add z y';

export const example1 = 'inp x\n' +
    'mul x -1';

export const example2 = 'inp z\n' +
    'inp x\n' +
    'mul z 3\n' +
    'eql z x';

export const example3 = 'inp w\n' +
    'add z w\n' +
    'mod z 2\n' +
    'div w 2\n' +
    'add y w\n' +
    'mod y 2\n' +
    'div w 2\n' +
    'add x w\n' +
    'mod x 2\n' +
    'div w 2\n' +
    'mod w 2';

export const example4 = 'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 1\n' +
    'add x 11\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 5\n' +
    'mul y x\n' +
    'add z y';

export const example5 = 'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 1\n' +
    'add x 11\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 5\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 1\n' +
    'add x 13\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 5\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 1\n' +
    'add x 12\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 1\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 1\n' +
    'add x 15\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 15\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 1\n' +
    'add x 10\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 2\n' +
    'mul y x\n' +
    'add z y\n' +
    'inp w\n' +
    'mul x 0\n' +
    'add x z\n' +
    'mod x 26\n' +
    'div z 26\n' +
    'add x -1\n' +
    'eql x w\n' +
    'eql x 0\n' +
    'mul y 0\n' +
    'add y 25\n' +
    'mul y x\n' +
    'add y 1\n' +
    'mul z y\n' +
    'mul y 0\n' +
    'add y w\n' +
    'add y 2\n' +
    'mul y x\n' +
    'add z y';