const input = 'acc +42\n' +
    'acc -12\n' +
    'nop +112\n' +
    'acc +47\n' +
    'jmp +600\n' +
    'acc +21\n' +
    'jmp +1\n' +
    'acc +0\n' +
    'acc +50\n' +
    'jmp +16\n' +
    'acc +10\n' +
    'jmp +56\n' +
    'acc -5\n' +
    'nop +179\n' +
    'nop +36\n' +
    'jmp +341\n' +
    'acc -12\n' +
    'nop +580\n' +
    'acc -9\n' +
    'jmp +112\n' +
    'acc +12\n' +
    'acc +6\n' +
    'acc +40\n' +
    'acc +1\n' +
    'jmp +237\n' +
    'acc +50\n' +
    'jmp +61\n' +
    'nop +542\n' +
    'jmp +644\n' +
    'nop +598\n' +
    'nop +280\n' +
    'acc +34\n' +
    'acc +10\n' +
    'jmp +486\n' +
    'acc +34\n' +
    'nop +152\n' +
    'acc +35\n' +
    'jmp +629\n' +
    'acc +37\n' +
    'jmp +447\n' +
    'acc +50\n' +
    'nop +522\n' +
    'acc +43\n' +
    'jmp +271\n' +
    'jmp +451\n' +
    'acc +27\n' +
    'jmp +1\n' +
    'acc +24\n' +
    'nop +532\n' +
    'jmp +494\n' +
    'acc +39\n' +
    'acc -10\n' +
    'acc +42\n' +
    'acc -9\n' +
    'jmp +54\n' +
    'acc +36\n' +
    'jmp +236\n' +
    'acc +34\n' +
    'acc +47\n' +
    'nop +613\n' +
    'acc +27\n' +
    'jmp +561\n' +
    'acc +3\n' +
    'acc -5\n' +
    'acc +11\n' +
    'acc +19\n' +
    'jmp +111\n' +
    'acc +32\n' +
    'nop -52\n' +
    'jmp +108\n' +
    'acc -16\n' +
    'acc +40\n' +
    'jmp +207\n' +
    'nop -44\n' +
    'acc +47\n' +
    'jmp +159\n' +
    'nop +150\n' +
    'acc +43\n' +
    'acc +7\n' +
    'jmp +200\n' +
    'nop +141\n' +
    'acc +2\n' +
    'jmp +487\n' +
    'acc +27\n' +
    'nop +122\n' +
    'nop +519\n' +
    'jmp +22\n' +
    'nop +27\n' +
    'nop +251\n' +
    'acc -2\n' +
    'jmp +171\n' +
    'acc -11\n' +
    'jmp +242\n' +
    'acc +14\n' +
    'acc -11\n' +
    'jmp +540\n' +
    'acc -5\n' +
    'acc +47\n' +
    'acc +14\n' +
    'jmp +252\n' +
    'acc +34\n' +
    'acc +28\n' +
    'acc +1\n' +
    'jmp +311\n' +
    'jmp +1\n' +
    'acc +28\n' +
    'acc +0\n' +
    'jmp +321\n' +
    'acc +23\n' +
    'acc +8\n' +
    'acc +26\n' +
    'acc +0\n' +
    'jmp +202\n' +
    'jmp +541\n' +
    'acc +21\n' +
    'acc -9\n' +
    'acc +7\n' +
    'jmp +81\n' +
    'acc +5\n' +
    'acc +31\n' +
    'acc -16\n' +
    'jmp +56\n' +
    'acc -1\n' +
    'acc +21\n' +
    'acc +45\n' +
    'acc -7\n' +
    'jmp +278\n' +
    'acc +0\n' +
    'acc +2\n' +
    'acc -4\n' +
    'jmp +514\n' +
    'acc -1\n' +
    'acc -16\n' +
    'acc +32\n' +
    'jmp +248\n' +
    'acc +25\n' +
    'jmp +333\n' +
    'acc -18\n' +
    'acc +0\n' +
    'acc +25\n' +
    'acc +43\n' +
    'jmp +416\n' +
    'acc +18\n' +
    'nop -127\n' +
    'acc +37\n' +
    'acc -4\n' +
    'jmp +495\n' +
    'nop +16\n' +
    'jmp +1\n' +
    'jmp +320\n' +
    'acc +22\n' +
    'jmp +453\n' +
    'acc -3\n' +
    'nop +519\n' +
    'nop +49\n' +
    'jmp +32\n' +
    'jmp -89\n' +
    'acc +11\n' +
    'acc +31\n' +
    'jmp +454\n' +
    'acc +12\n' +
    'acc +32\n' +
    'jmp +283\n' +
    'acc -2\n' +
    'nop +411\n' +
    'jmp -65\n' +
    'acc +0\n' +
    'nop +25\n' +
    'acc +5\n' +
    'acc +0\n' +
    'jmp +284\n' +
    'acc -15\n' +
    'jmp +1\n' +
    'jmp +166\n' +
    'acc +27\n' +
    'acc +50\n' +
    'jmp +91\n' +
    'jmp -104\n' +
    'nop +71\n' +
    'jmp +358\n' +
    'acc +15\n' +
    'acc +1\n' +
    'jmp -60\n' +
    'acc +20\n' +
    'acc +6\n' +
    'acc +10\n' +
    'jmp +228\n' +
    'acc -3\n' +
    'jmp +316\n' +
    'acc +5\n' +
    'acc +11\n' +
    'jmp +254\n' +
    'acc -3\n' +
    'acc +20\n' +
    'jmp +194\n' +
    'acc +9\n' +
    'acc -8\n' +
    'jmp +6\n' +
    'acc +30\n' +
    'jmp +376\n' +
    'acc -19\n' +
    'acc -8\n' +
    'jmp -122\n' +
    'jmp +3\n' +
    'nop -41\n' +
    'jmp -68\n' +
    'jmp -119\n' +
    'nop +434\n' +
    'acc -16\n' +
    'nop -199\n' +
    'acc +37\n' +
    'jmp +68\n' +
    'acc +3\n' +
    'acc +18\n' +
    'acc +38\n' +
    'acc -8\n' +
    'jmp +327\n' +
    'nop +110\n' +
    'acc +9\n' +
    'acc +31\n' +
    'jmp -8\n' +
    'jmp +130\n' +
    'acc +20\n' +
    'acc -1\n' +
    'nop +16\n' +
    'jmp +24\n' +
    'nop +14\n' +
    'nop -40\n' +
    'nop -57\n' +
    'acc +10\n' +
    'jmp +239\n' +
    'nop +164\n' +
    'nop +196\n' +
    'jmp -208\n' +
    'acc -12\n' +
    'jmp +284\n' +
    'acc +10\n' +
    'acc +27\n' +
    'jmp +1\n' +
    'jmp -195\n' +
    'acc +1\n' +
    'acc +10\n' +
    'acc +25\n' +
    'acc -17\n' +
    'jmp +25\n' +
    'acc +42\n' +
    'acc +1\n' +
    'acc -3\n' +
    'jmp -148\n' +
    'jmp -28\n' +
    'acc +34\n' +
    'nop -222\n' +
    'acc +3\n' +
    'acc +15\n' +
    'jmp +115\n' +
    'acc +26\n' +
    'acc +36\n' +
    'acc +33\n' +
    'jmp -248\n' +
    'acc -14\n' +
    'jmp -89\n' +
    'acc +19\n' +
    'acc -14\n' +
    'acc +34\n' +
    'jmp +380\n' +
    'jmp +1\n' +
    'jmp -5\n' +
    'jmp +187\n' +
    'jmp +236\n' +
    'acc -4\n' +
    'acc +47\n' +
    'jmp +2\n' +
    'jmp +232\n' +
    'jmp +1\n' +
    'acc -8\n' +
    'jmp +397\n' +
    'acc +7\n' +
    'acc +2\n' +
    'jmp +136\n' +
    'jmp +325\n' +
    'acc +11\n' +
    'acc -17\n' +
    'acc -4\n' +
    'jmp -43\n' +
    'acc +20\n' +
    'acc -9\n' +
    'jmp +60\n' +
    'acc +36\n' +
    'acc +49\n' +
    'nop +333\n' +
    'acc +38\n' +
    'jmp -169\n' +
    'acc +2\n' +
    'acc +8\n' +
    'jmp +82\n' +
    'acc +6\n' +
    'jmp -159\n' +
    'acc +25\n' +
    'acc +23\n' +
    'acc +18\n' +
    'acc +41\n' +
    'jmp -138\n' +
    'jmp -145\n' +
    'acc +49\n' +
    'acc +37\n' +
    'jmp +123\n' +
    'acc +2\n' +
    'nop +179\n' +
    'acc -19\n' +
    'jmp -152\n' +
    'jmp -294\n' +
    'acc +50\n' +
    'acc +50\n' +
    'jmp -46\n' +
    'acc +17\n' +
    'jmp -158\n' +
    'acc -11\n' +
    'acc +5\n' +
    'acc -6\n' +
    'jmp +278\n' +
    'acc +3\n' +
    'acc +26\n' +
    'acc +27\n' +
    'acc +24\n' +
    'jmp -69\n' +
    'acc +22\n' +
    'jmp +204\n' +
    'acc +15\n' +
    'acc +49\n' +
    'acc +1\n' +
    'acc +22\n' +
    'jmp +149\n' +
    'acc +31\n' +
    'jmp +131\n' +
    'jmp -309\n' +
    'acc +40\n' +
    'acc +39\n' +
    'acc +44\n' +
    'jmp -216\n' +
    'acc +15\n' +
    'acc +17\n' +
    'jmp +54\n' +
    'nop +157\n' +
    'acc +24\n' +
    'acc +18\n' +
    'jmp -111\n' +
    'acc -6\n' +
    'jmp +22\n' +
    'acc +17\n' +
    'acc -3\n' +
    'jmp -228\n' +
    'acc -2\n' +
    'acc +41\n' +
    'jmp +235\n' +
    'nop +234\n' +
    'jmp -82\n' +
    'nop -83\n' +
    'acc +44\n' +
    'acc +39\n' +
    'nop +216\n' +
    'jmp -180\n' +
    'jmp -163\n' +
    'acc +13\n' +
    'acc +0\n' +
    'jmp +1\n' +
    'jmp +301\n' +
    'acc +14\n' +
    'nop -187\n' +
    'jmp -181\n' +
    'acc +48\n' +
    'nop +169\n' +
    'acc +27\n' +
    'jmp -334\n' +
    'nop -226\n' +
    'acc +3\n' +
    'jmp -61\n' +
    'jmp +1\n' +
    'acc -15\n' +
    'jmp -175\n' +
    'acc +9\n' +
    'acc +19\n' +
    'jmp +223\n' +
    'acc +20\n' +
    'acc +39\n' +
    'acc +50\n' +
    'acc +13\n' +
    'jmp -119\n' +
    'jmp +240\n' +
    'acc +50\n' +
    'acc +40\n' +
    'acc -14\n' +
    'jmp +236\n' +
    'acc +0\n' +
    'acc +0\n' +
    'jmp +34\n' +
    'acc +20\n' +
    'acc -3\n' +
    'nop -136\n' +
    'acc +4\n' +
    'jmp -370\n' +
    'acc +38\n' +
    'acc +25\n' +
    'acc +9\n' +
    'jmp -240\n' +
    'jmp +1\n' +
    'acc -10\n' +
    'acc +21\n' +
    'acc +46\n' +
    'jmp +118\n' +
    'acc -8\n' +
    'acc +12\n' +
    'nop +64\n' +
    'acc +0\n' +
    'jmp +253\n' +
    'acc +32\n' +
    'acc -6\n' +
    'acc +44\n' +
    'jmp +115\n' +
    'acc +36\n' +
    'acc +23\n' +
    'acc +21\n' +
    'nop +88\n' +
    'jmp -275\n' +
    'acc +8\n' +
    'jmp -127\n' +
    'acc +5\n' +
    'acc +42\n' +
    'jmp +82\n' +
    'acc +41\n' +
    'acc +31\n' +
    'acc +45\n' +
    'acc +20\n' +
    'jmp +131\n' +
    'acc +21\n' +
    'acc +7\n' +
    'jmp +97\n' +
    'acc +12\n' +
    'acc +0\n' +
    'nop +61\n' +
    'acc +36\n' +
    'jmp -106\n' +
    'acc +20\n' +
    'acc -1\n' +
    'acc -14\n' +
    'jmp -210\n' +
    'acc -12\n' +
    'acc -19\n' +
    'acc -19\n' +
    'jmp -25\n' +
    'acc -11\n' +
    'nop -247\n' +
    'acc +0\n' +
    'acc +7\n' +
    'jmp -290\n' +
    'acc +36\n' +
    'acc +43\n' +
    'acc +8\n' +
    'nop -154\n' +
    'jmp -102\n' +
    'acc +8\n' +
    'acc +31\n' +
    'acc +44\n' +
    'acc -5\n' +
    'jmp -184\n' +
    'jmp -252\n' +
    'acc +50\n' +
    'acc +18\n' +
    'acc +5\n' +
    'jmp -141\n' +
    'jmp -159\n' +
    'acc -4\n' +
    'acc +8\n' +
    'acc +4\n' +
    'acc -5\n' +
    'jmp +56\n' +
    'acc +19\n' +
    'acc +46\n' +
    'jmp +53\n' +
    'acc +45\n' +
    'jmp -316\n' +
    'acc -5\n' +
    'acc -1\n' +
    'nop +98\n' +
    'jmp +195\n' +
    'jmp +1\n' +
    'jmp +58\n' +
    'acc +15\n' +
    'nop -471\n' +
    'acc +14\n' +
    'jmp +48\n' +
    'nop -269\n' +
    'nop +8\n' +
    'nop -223\n' +
    'acc +24\n' +
    'jmp -288\n' +
    'jmp +85\n' +
    'nop -1\n' +
    'jmp +1\n' +
    'jmp +45\n' +
    'acc +48\n' +
    'nop -490\n' +
    'acc +0\n' +
    'jmp +37\n' +
    'jmp +132\n' +
    'acc +5\n' +
    'jmp -256\n' +
    'acc +12\n' +
    'acc +22\n' +
    'jmp -479\n' +
    'acc +15\n' +
    'nop -56\n' +
    'acc -18\n' +
    'acc -6\n' +
    'jmp -157\n' +
    'nop +16\n' +
    'acc +5\n' +
    'acc +26\n' +
    'acc +42\n' +
    'jmp -172\n' +
    'acc -13\n' +
    'acc -2\n' +
    'jmp -237\n' +
    'acc +9\n' +
    'acc -10\n' +
    'acc -16\n' +
    'jmp +32\n' +
    'acc +11\n' +
    'acc +3\n' +
    'jmp -208\n' +
    'jmp -449\n' +
    'jmp -383\n' +
    'jmp +96\n' +
    'acc -9\n' +
    'acc -14\n' +
    'jmp -30\n' +
    'nop -36\n' +
    'jmp +21\n' +
    'jmp +117\n' +
    'jmp -169\n' +
    'jmp -387\n' +
    'acc -5\n' +
    'acc -9\n' +
    'jmp -344\n' +
    'acc +13\n' +
    'acc +4\n' +
    'acc +45\n' +
    'jmp -219\n' +
    'acc +9\n' +
    'acc +44\n' +
    'acc +31\n' +
    'acc +16\n' +
    'jmp -71\n' +
    'jmp -77\n' +
    'acc -1\n' +
    'acc +40\n' +
    'acc +31\n' +
    'jmp -385\n' +
    'acc +1\n' +
    'jmp -255\n' +
    'nop -20\n' +
    'acc +0\n' +
    'acc +29\n' +
    'jmp -180\n' +
    'acc +13\n' +
    'acc +5\n' +
    'nop -292\n' +
    'jmp -204\n' +
    'acc +30\n' +
    'jmp -265\n' +
    'acc +19\n' +
    'acc +31\n' +
    'jmp -457\n' +
    'acc +16\n' +
    'acc +27\n' +
    'jmp +67\n' +
    'jmp +88\n' +
    'acc +20\n' +
    'acc +44\n' +
    'acc +27\n' +
    'jmp -40\n' +
    'acc +26\n' +
    'acc +48\n' +
    'acc +28\n' +
    'acc -12\n' +
    'jmp -120\n' +
    'acc -9\n' +
    'acc +42\n' +
    'jmp -543\n' +
    'acc +4\n' +
    'nop +83\n' +
    'acc +41\n' +
    'jmp -28\n' +
    'acc +40\n' +
    'acc -17\n' +
    'acc +14\n' +
    'acc -6\n' +
    'jmp -70\n' +
    'nop -294\n' +
    'acc -10\n' +
    'acc +9\n' +
    'acc +7\n' +
    'jmp -322\n' +
    'jmp +1\n' +
    'jmp -46\n' +
    'acc +0\n' +
    'acc +38\n' +
    'acc +6\n' +
    'jmp -381\n' +
    'acc +49\n' +
    'acc -16\n' +
    'acc +35\n' +
    'acc +45\n' +
    'jmp -184\n' +
    'acc -6\n' +
    'acc -13\n' +
    'acc +9\n' +
    'jmp -180\n' +
    'acc +18\n' +
    'acc +49\n' +
    'acc -4\n' +
    'nop -197\n' +
    'jmp -395\n' +
    'nop -266\n' +
    'jmp -530\n' +
    'acc +16\n' +
    'acc +9\n' +
    'jmp -117\n' +
    'acc -4\n' +
    'acc -7\n' +
    'acc +44\n' +
    'acc +35\n' +
    'jmp -122\n' +
    'acc +31\n' +
    'acc -5\n' +
    'jmp -503\n' +
    'jmp -555\n' +
    'acc +19\n' +
    'acc +25\n' +
    'acc -10\n' +
    'acc +50\n' +
    'jmp -493\n' +
    'jmp -591\n' +
    'acc +40\n' +
    'jmp -491\n' +
    'nop +28\n' +
    'nop -48\n' +
    'acc +11\n' +
    'nop -25\n' +
    'jmp -591\n' +
    'jmp +1\n' +
    'acc -15\n' +
    'acc +21\n' +
    'acc +46\n' +
    'jmp -199\n' +
    'jmp +1\n' +
    'acc +42\n' +
    'acc +10\n' +
    'acc -11\n' +
    'jmp -213\n' +
    'acc -8\n' +
    'acc +2\n' +
    'acc +36\n' +
    'jmp -470\n' +
    'acc +37\n' +
    'jmp -195\n' +
    'jmp -38\n' +
    'acc +17\n' +
    'jmp -26\n' +
    'nop -376\n' +
    'acc +27\n' +
    'acc +11\n' +
    'jmp -185\n' +
    'acc +44\n' +
    'acc +12\n' +
    'acc +9\n' +
    'acc +14\n' +
    'jmp -626\n' +
    'jmp -89\n' +
    'acc +45\n' +
    'acc +23\n' +
    'acc +13\n' +
    'acc +19\n' +
    'jmp +1';

const getAccumulatorCount = (instructions, visited) => {
    let i = 0;
    let accumulator = 0;
    let doesLoopExist = false;
    while (i < instructions.length) {
        const instruction = instructions[i].split(' ');
        if (visited[i]) {
            doesLoopExist = true;
            return {accumulator,doesLoopExist};
        } else {
            visited[i] = 1;
        }
        if (instruction[0] === 'acc') {
            accumulator += parseInt(instruction[1]);
            i++;
        } else if (instruction[0] === 'jmp') {
            i += parseInt(instruction[1]);
        } else if (instruction[0] === 'nop') {
            i++;
        }
    }

    return {accumulator, doesLoopExist};
};

const part1Solution = (input) => {
    const instructions = input.split('\n');
    const visited = {};
    const {accumulator} = getAccumulatorCount(instructions, visited);

    return accumulator;
};

const part2Solution = (input) => {
    const instructions = input.split('\n');
    const map = {'nop': [], 'jmp': []};
    for (let i = 0; i < instructions.length; i++) {
        const instruction = instructions[i].split(' ');
        if (instruction[0] === 'jmp') {
            map['jmp'].push(i);
        } else if (instruction[0] === 'nop') {
            map['nop'].push(i);
        }
    }
    const keys = Object.keys(map);

    for (let i = 0; i < keys.length; i++) {
        for (let j = 0; j < map[keys[i]].length; j++) {
            const visited = {};
            const newInstructions = [...instructions];
            const newInstruction = keys[i] === 'nop' ? instructions[map[keys[i]][j]].replace('nop', 'jmp') :
                instructions[map[keys[i]][j]].replace('jmp', 'nop');
            newInstructions[map[keys[i]][j]] = newInstruction;
            const {accumulator, doesLoopExist} = getAccumulatorCount(newInstructions, visited);
            if (!doesLoopExist) {
                return accumulator;
            }
        }
    }

    console.log(map);
};

console.log(part1Solution(input));
console.log(part2Solution(input));

